# -*- coding: utf-8 -*-
"""Copy of Assignment2.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OykLubLDEJnn5Nj5tYfES4G2pPA7igRq
"""

!pip uninstall -y langchain langchain-core langchain-community langchain-text-splitters langsmith langchain-groq langgraph langgraph-prebuilt

!pip install -q langchain==0.2.16
!pip install -q langchain-core==0.2.43
!pip install -q langchain-community==0.2.16
!pip install -q langchain-text-splitters==0.2.4
!pip install -q langsmith==0.1.147
!pip install -q langchain-groq==0.1.5
!pip install -q sentence-transformers
!pip install -q faiss-cpu
!pip install -q pypdf
!pip install gradio
!pip install -q markdown unstructured

import os
import math
import json
import pandas as pd

from langchain_groq import ChatGroq
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.document_loaders import PyPDFLoader, CSVLoader, JSONLoader, UnstructuredMarkdownLoader
from langchain.vectorstores import FAISS
from langchain.embeddings import HuggingFaceEmbeddings

from langchain.schema import Document
from google.colab import files

os.environ["GROQ_API_KEY"] = ""

llm = ChatGroq(
    model_name="llama-3.3-70b-versatile",
    temperature=0.2
)

# Fix: Address numpy dependency conflict and ensure sentence-transformers is installed.
# Explicitly installing numpy==1.26.4 to resolve conflicts with langchain and langchain-community.
!pip install --upgrade --force-reinstall numpy==1.26.4
!pip install --upgrade --force-reinstall sentence-transformers

embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

def compute_confidence(query, answer, context):

    # LLM self-eval
    llm_score_map = {"High": 0.9, "Medium": 0.6, "Low": 0.3}
    llm_conf = llm_confidence(query, answer, context)

    # Retrieval confidence
    docs_scores = vector_db.similarity_search_with_score(query, k=5)
    avg_score = sum(score for _, score in docs_scores) / len(docs_scores)
    retrieval_conf = 1 / (1 + avg_score)

    final_score = (llm_score_map[llm_conf] * 0.6) + (retrieval_conf * 0.4)

    if final_score > 0.7:
        return "High"
    elif final_score > 0.4:
        return "Medium"
    else:
        return "Low"

def llm_confidence(query, answer, context):

    prompt = f"""
    Evaluate the confidence of the following answer.

    Question: {query}
    Answer: {answer}

    Context:
    {context}

    Give a confidence score between 0 and 100.
    Only return the number.
    """

    response = llm.invoke(prompt)

    try:
        score = float(response.content.strip())
    except:
        score = 50

    if score >= 70:
        return "High"
    elif score >= 40:
        return "Medium"
    else:
        return "Low"

def classify_summary_type(query):

    prompt = f"""
    Determine the type of summary requested.

    Query: {query}

    Respond with ONLY one of the following labels:
    - document_summary
    - topic_summary

    If the user is asking to summarize a specific concept or subject, return topic_summary.
    If the user is asking to summarize the entire document(s), return document_summary.
    """

    response = llm.invoke(prompt)

    return response.content.strip().lower()

def summarize_document(query):

    summary_type = classify_summary_type(query)

    # TOPIC SUMMARY
    if summary_type == "topic_summary":

        retrieved_docs = retriever.get_relevant_documents(query)[:10]

        context = "\n".join([doc.page_content for doc in retrieved_docs])

        prompt = f"""
        Write a concise summary of the following topic using the context below.

        Topic Query:
        {query}

        Context:
        {context}
        """

        response = llm.invoke(prompt)

        confidence = compute_confidence(query,response,context)

        citations = list(set(
            doc.metadata.get("source","unknown")
            for doc in retrieved_docs
        ))

        return response.content, citations, confidence


    # DOCUMENT SUMMARY
    else:

        batch_size = 50
        chunk_summaries = []

        for i in range(0, len(documents), batch_size):

            batch = documents[i:i+batch_size:5]

            batch_text = "\n".join(
                doc.page_content for doc in batch
            )

            prompt = f"""
            Summarize the following section of a document:

            {batch_text}
            """

            response = llm.invoke(prompt)

            chunk_summaries.append(response.content)


        combined_summary = "\n".join(chunk_summaries)

        final_prompt = f"""
        The following are summaries of different parts of a document.

        {combined_summary}

        Write a concise overall summary of the entire document.
        """

        final_response = llm.invoke(final_prompt)

        confidence = compute_confidence(query,final_response,combined_summary)

        citations = list(set(
            doc.metadata.get("source","unknown")
            for doc in documents
        ))

        return final_response.content, citations, confidence

def qa_tool(query):

    retrieved_docs = retriever.get_relevant_documents(query)

    context = "\n".join([doc.page_content for doc in retrieved_docs])

    prompt = f"""
    Answer the question using ONLY the context below.

    Context:
    {context}

    Question:
    {query}
    """

    response = llm.invoke(prompt)

    confidence = compute_confidence(query,response,context)

    citations = list(set([doc.metadata.get("source","unknown") for doc in retrieved_docs]))

    return response.content, citations, confidence

def analytical_tool(query):

    retrieved_docs = retriever.get_relevant_documents(query)

    context = "\n".join([doc.page_content for doc in retrieved_docs])

    prompt = f"""
    Analyze and compare the information across the following documents.

    Context:
    {context}

    Question:
    {query}

    Provide correlations, similarities, and differences if applicable.
    """

    response = llm.invoke(prompt)

    confidence = compute_confidence(query,response,context)

    citations = list(set([doc.metadata.get("source","unknown") for doc in retrieved_docs]))

    return response.content, citations, confidence

def agent_router(query):
    router_prompt = f"""
    Decide which tool should answer the user query.

    Tools:
    summarize_document → for summaries of documents or topics from various documents
    compare_document → for comparing or analysing or correlating multiple documents
    document_qa → for answering questions about one or multiple documents

    Query: {query}

    Return only the tool name.
    """

    tool_choice = llm.invoke(router_prompt).content.lower()

    if "summarize" in tool_choice:
        tool = "Summarizer Tool"
        answer, citations, confidence = summarize_document(query)

    elif "compare" in tool_choice:
        tool = "Comparative / Analytical Tool"
        answer, citations, confidence = analytical_tool(query)

    else:
        tool = "Q&A Tool"
        answer, citations, confidence = qa_tool(query)


    return {
        "Response": answer,
        "Tool Used": tool,
        "Citations": citations,
        "Confidence": confidence
    }

import gradio as gr
import os

# -------------------------------
# GLOBAL STORAGE
# -------------------------------
vector_db = None
documents = None


# -------------------------------
# FILE PROCESSING FUNCTION
# -------------------------------
def process_files(files):

    global vector_db, documents

    docs = []

    for file in files:
        file_path = file.name

        if file_path.endswith(".pdf"):
            loader = PyPDFLoader(file_path)
            docs.extend(loader.load())

        elif file_path.endswith(".csv"):
            loader = CSVLoader(file_path)
            docs.extend(loader.load())

        elif file_path.endswith(".json"):
            loader = JSONLoader(file_path=file_path, jq_schema='.', text_content=False)
            docs.extend(loader.load())

        elif file_path.endswith(".md"):
            loader = UnstructuredMarkdownLoader(file_path)
            docs.extend(loader.load())

    # Chunking
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=800,
        chunk_overlap=100
    )

    documents = text_splitter.split_documents(docs)

    # Create FAISS DB
    vector_db = FAISS.from_documents(documents, embedding_model)
    retriever = vector_db.as_retriever(search_kwargs={"k":10})


    return f"{len(files)} files processed | {len(documents)} chunks created"


# -------------------------------
# QUERY FUNCTION
# -------------------------------
def handle_query(query):

    if vector_db is None:
        return "Upload documents first!", "", "", ""

    result = agent_router(query)

    response = result["Response"]
    tool = result["Tool Used"]
    citations = "\n".join(result["Citations"])
    confidence = result["Confidence"]

    return response, tool, citations, confidence


# -------------------------------
# GRADIO UI
# -------------------------------
with gr.Blocks(title="Agentic RAG System") as demo:

    gr.Markdown("## 📄 Agentic RAG System")

    with gr.Row():
        file_input = gr.File(
            file_count="multiple",
            label="Upload Documents (PDF, CSV, JSON, Markdown)"
        )

    upload_btn = gr.Button("Process Documents")

    upload_status = gr.Textbox(label="Upload Status")

    upload_btn.click(
        fn=process_files,
        inputs=file_input,
        outputs=upload_status
    )

    gr.Markdown("### 🔍 Ask Questions")

    query_input = gr.Textbox(
        label="Enter your query",
        placeholder="Ask something about your documents..."
    )

    ask_btn = gr.Button("Run Query")

    # OUTPUT SECTION
    with gr.Row():
        response_box = gr.Textbox(label="Response", lines=10)
        tool_box = gr.Textbox(label="Tool Used")

    with gr.Row():
        citations_box = gr.Textbox(label="Citations", lines=5)
        confidence_box = gr.Textbox(label="Confidence")

    ask_btn.click(
        fn=handle_query,
        inputs=query_input,
        outputs=[
            response_box,
            tool_box,
            citations_box,
            confidence_box
        ]
    )

demo.launch(debug=True)

